apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ado-agent-scaler
  namespace: vsts-agent
spec:
  scaleTargetRef:
    name: ado-agent
    kind: StatefulSet
    apiVersion: apps/v1
  pollingInterval: 10
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 5
  fallback:
    failureThreshold: 3
    replicas: 2
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
    - type: azure-pipelines
      metadata:
        poolName: "devops pools"  # or use poolID: "11"
        targetPipelinesQueueLength: "1"
        activationTargetPipelinesQueueLength: "0"
        jobsToFetch: "100"
      authenticationRef:
        name: pipeline-trigger-auth